import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { DashboardNav } from "@/components/dashboard-nav";
import { dashboardConfig } from "@/config/dashboard";
import { MainNav } from "@/components/main-nav";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex h-screen overflow-hidden">
          <aside
            className={`z-50 flex h-screen w-[200px] flex-col overflow-y-hidden bg-[#1E2640] static`}
          >
            <DashboardNav items={dashboardConfig.sidebarNav} />
          </aside>
          <div className="relative flex flex-1 flex-col overflow-y-auto overflow-x-hidden">
            <header>
              <MainNav items={dashboardConfig.mainNav} />
            </header>
            <main>
              <div className="mx-auto max-w-screen-2xl p-4 md:p-6 2xl:p-10">
                {children}
              </div>
            </main>
          </div>
        </div>
      </body>
    </html>
  );
}
