import {
  Home,
  ClipboardList,
  LayoutGrid,
  Truck,
  Volume2,
  ArrowUpDown,
  ChevronDown,
  LineChart,
  Wallet,
  Search,
  Mails,
  Palette,
  Play,
  Download,
  MousePointer2,
  BadgePercent,
  Zap,
  UsersRound,
  type LucideIcon as LucideIcon,
} from "lucide-react";

export type Icon = LucideIcon;

export const Icons = {
  Home,
  Orders: ClipboardList,
  Products: LayoutGrid,
  Delivery: Truck,
  Search,
  Marketing: Volume2,
  Mails,
  Tools: MousePointer2,
  Discounts: BadgePercent,
  Audience: UsersRound,
  Appearance: Palette,
  Payments: Wallet,
  ArrowDown: ChevronDown,
  Sort: ArrowUpDown,
  Download: Download,
  Play,
  Plugins: Zap,
  Analytics: LineChart,
};
